### ISSUE TITLE
Is there a 'all post list' page?

### ISSUE THREAD

**Issue by walfud** [pages-themes/slate#23]
Hi, I like your theme very well. But after I fork & deploy to my github-pages, and have some article, I even can't have a index page for all my posts. That's a pity.
Is there anyway to generate directory for all my post automatically?
Thanks in advance.

**Comment by ahuglajbclajep** [comment]
Have you tried this?
https://jekyllrb.com/docs/posts/#displaying-an-index-of-posts

**Comment by walfud** [comment]
I'll try. Thanks
