### ISSUE TITLE
"View on Github" doesn't respect the 'is project page" flag

### ISSUE THREAD

**Issue by NeilW** [pages-themes/slate#24]
The View on Github link appears regardless of whether the is_project_page flag is set or not.

needs a

`{% if site.github.is_project_page %}`

wrap.

**Comment by NeilW** [comment]
Heh. Looks like the outstanding PR request fixes this problem. Just need reviewing

**Comment by elamje** [comment]
Is there any reason that this would still be an issue now?

**Comment by martinzugec-ctx** [comment]
As far as I can say, this has not been fixed. I have is_project_page defined, however button is still visible :(

**Comment by g-easy** [comment]
It looks like the `github-pages` gem pins `jekyll-theme-slate` to release 0.1.1 from Apr 2018, which doesn't include the fix.

Could someone please make a new release of slate? cc @benbalter

**Comment by albertomsp** [comment]
I'm also having the same problem with the "View on GitHub" being shown even with the `is_project_page` defined. Shall this issue be reopened until the problem is fixed?

**Comment by ddhendriks** [comment]
This issue still does not seem resolved

**Comment by ahmad88me** [comment]
I had the same issue.
I copied the workaround from here https://github.com/pages-themes/cayman/issues/79
and added ```#forkme_banner{
  display: none !important;
}``` 
after the line `@import "{{ site.theme }}";`
 and it worked for me. I hope others might find it helpful too.
