### ISSUE TITLE
Double colon ::pseudo is highlighted as error

### ISSUE THREAD

**Issue by cliffasaurus** [pages-themes/slate#28]
Syntax highlighting does not seem to recognize double colon pseudo elements. I read that jekyll uses rouge and saw that this was an issue before at rouge https://github.com/jneen/rouge/pull/212 and this was closed there. Not sure if this is the correct place to submit this issue.
![image](https://user-images.githubusercontent.com/34718818/49496560-39ec2300-f8a1-11e8-8727-1f005d828550.png)

**Comment by ahuglajbclajep** [comment]
GitHub Pages is generated in the same environment as [pages-gem](https://github.com/github/pages-gem).
This problem seems to be related to the following issue.
https://github.com/github/pages-gem/issues/601

**Comment by cliffasaurus** [comment]
The issue seems to have been fixed in v1.7.5 though. (Which has been long before 2.2.1) https://github.com/jneen/rouge/pull/212#issuecomment-68061745
