### ISSUE TITLE
Invalid theme folder

### ISSUE THREAD

**Issue by BashfulBandit** [pages-themes/slate#31]
I am using the Jekyll Slate Theme on my documentation site and so far love it. The only issue is when I run `bundle exec jekyll serve` locally, I receive a warning saying, "Invalid theme folder: _includes". The warning appears twice. It doesn't affect the building of the site at all, but I can't figure out what exactly is causing it. If I comment out in my `_config.yml` file the line which defines the theme to use, then the warnings go a way, but obviously the site/theme doesn't work then. I am not sure if this only happens locally or if it also happens when I push to GitHub and the site is built for GitHub Pages. Am I missing something?

**Comment by calebx** [comment]
i have the same issue here.

**Comment by AnnYe-Fluithaas** [comment]
Looks like the Slate theme doesn't use `_includes` in the theme. I can see this by navigating to the Gem folder  
* On Mac: `open $(bundle info --path jekyll-theme-slate)`  
* On Windows: `explorer C:\Ruby26-x64\lib\ruby\gems\2.6.0\gems\jekyll-theme-slate-0.1.1`

If you compare it with the minima folder, then you see that Slate doesn't have `_includes`, and also in the `_layouts` folder, it only has "default.html", while minima has additional layout types.

Now I'm not sure if that means the developers of Slate are just expecting us [to create our own theme folders and files for our project](https://jekyllrb.com/docs/themes/#overriding-theme-defaults)?  That makes me uncertain of how to actually view the Slate visual theme for my GitHub Pages.
