### ISSUE TITLE
Show "View on GitHub" on project pages only doesn't work...

### ISSUE THREAD

**Issue by rafaelurben** [pages-themes/slate#35]
Is also shows up if it isn't a project page and also if 
```
github:
  is_project_page: false
```
is in "_config.yml"

**Comment by PaulCoral** [comment]
Hi,
I would also need this fix

**Comment by PaulCoral** [comment]
> Is also shows up if it isn't a project page and also if
> 
> ```
> github:
>   is_project_page: false
> ```
> 
> is in "_config.yml"

@rafaelurben 
Seems like it works like this 
```yaml
site:
  github:
    is_project_page: false
```

**Comment by rafaelurben** [comment]
Oh, I actually forgot about this issue 😂 I just modified the template so I don't need this anymore 🤷 But thank you anyway!
