### ISSUE TITLE
Code block

### ISSUE THREAD

**Issue by jwwangchn** [pages-themes/slate#5]
Excuse me, how to modify the configuration file to remove gray border around a block of code? I personally prefer a solid color blocks of code.
![image](https://cloud.githubusercontent.com/assets/18238763/23113866/175765da-f776-11e6-9e33-5651bbb35e78.png)

**Comment by benbalter** [comment]
You'll need to customize the stylesheet by following [these instructions](https://github.com/pages-themes/slate#stylesheet).
