### ISSUE TITLE
Accessibility Issues

### ISSUE THREAD

**Issue by mgifford** [pages-themes/slate#8]
1) Would be important to have the language of the page in the header
2) Make the links a darker blue so that they meet color contrast requirements.

**Comment by benbalter** [comment]
Thanks @mgifford! Any interest in submitting a pull request with either or both of those improvements?

**Comment by mgifford** [comment]
with better contrast https://github.com/pages-themes/slate/pull/9

very similar to:
https://github.com/pages-themes/minimal/issues/10

**Comment by benbalter** [comment]
@mgifford can this be closed or are there still outstanding issues?

**Comment by mgifford** [comment]
Let's close it for now. I can re-open it if there's a future issue.

**Comment by benbalter** [comment]
❤️ Thanks.
